name: CI

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

permissions:
  contents: write # Explicitly grant write permission to the GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config user.name "${{ secrets.USERNAME }}"
        git config user.email "${{ secrets.EMAIL }}"

    - name: Make a commit
      run: |
        echo " " >> README.md
        git add README.md
        git commit -m "Always green!"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
